#
# Archivo de flujo de trabajo (pipeline) de GitHub Actions para CI/CD en multicloud (AWS y Azure)
#
name: SRI - CI/CD Pipeline Multi-Cloud (AWS & Azure)

on:
  push:
    branches: [ "master" ]
    paths:
      - '**.py' # Se dispara solo si modificas el archivo de la app

env:
  # Variables de entorno para AWS
  AWS_REGION: us-east-1
  ECR_REPOSITORY: sri-app-py
  # Variables de entorno para GitOps
  IMAGE_NAME: sri-ms-ipy-app
  REPOSITORY_NAME: 'patrickcuascota-beep/sri-config-gitops-test'
  REF: 'master' # branch de GitOps

jobs:
  # Job 1: Se ejecuta para la integración con AWS
  ci-cd-aws:
    runs-on: ubuntu-latest

    steps:
    # Step 1. Clonar el código fuente del repositorio principal
    - name: Clonar código fuente
      uses: actions/checkout@v4
    
    # Step 2. Leer la versión actual del proyecto desde el archivo VERSION
    - name: Leer versión actual del proyecto
      id: version
      run: |
        if [ -f VERSION ]; then
          CURRENT_VERSION=$(cat VERSION)
          echo "current_version=$CURRENT_VERSION" >> $GITHUB_OUTPUT
        else
          echo "current_version=1.0.0" >> $GITHUB_OUTPUT
        fi
    
    # Step 3. Instalar dependencias y ejecutar tests con pytest
    - name: Instalar dependencias y ejecutar tests
      run: |
        set -e
        pip install -r requirements.txt pytest pytest-cov
        # pytest /tests/ -v --cov=application --cov-report=xml

    # Step 4. Conectarse a AWS de forma segura
    - name: Configurar credenciales de AWS
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: ${{ env.AWS_REGION }} # Región de AWS

    # Step 5. Iniciar sesión en Amazon ECR para poder subir la imagen Docker
    - name: Iniciar sesión en Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    # Step 6. Construir la imagen Docker usando el Hash del commit como versión única
    - name: Compilar y subir Imagen a AWS ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: ${{ env.ECR_REPOSITORY }} # Debe coincidir con el nombre en AWS
        IMAGE_TAG: ${{ github.sha }}-${{ steps.version.outputs.current_version }}
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        echo "NEW_IMAGE=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_ENV

    # Step 7. El paso GitOps: Actualizar el repositorio de k8s - ArgoCD
    - name: Clonar repositorio GitOps
      uses: actions/checkout@v4
      with:
        repository: ${{ env.REPOSITORY_NAME }}
        token: ${{ secrets.GH_PAT }}
        ref: ${{ env.REF }}
        path: gitops-repo # Directorio donde se clonará el repositorio GitOps

    # Step 8. Actualizar la etiqueta de la imagen en el YAML de Kubernetes
    - name: Actualizar etiqueta de imagen en el YAML de Kubernetes
      working-directory: gitops-repo
      run: |
        echo "Directorio actual: $(pwd)"
        cd k8s
        # Reemplaza la línea de la imagen vieja por la URL de la nueva imagen de AWS ECR
        sed -i "s|image: .*|image: ${{ env.NEW_IMAGE }}|g" deployment.yaml

    # Step 9. Actualizar versión para la próxima compilación
    - name: Actualizar versión para la próxima compilación
      if: github.event_name == 'push'
      run: |
        CURRENT=${{ steps.version.outputs.current_version }}
        MAJOR=$(echo $CURRENT | cut -d. -f1)
        MINOR=$(echo $CURRENT | cut -d. -f2)
        PATCH=$(echo $CURRENT | cut -d. -f3)
        NEW_PATCH=$((PATCH + 1))
        NEW_VERSION="${MAJOR}.${MINOR}.${NEW_PATCH}"
        
        echo $NEW_VERSION > VERSION
        echo "Version: $CURRENT to $NEW_VERSION"

    # Step 10. Confirmar cambios en GitOps
    - name: Confirmar cambios en GitOps
      working-directory: gitops-repo
      if: github.event_name == 'push'
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        # Pull para evitar conflictos en ramapor multi-user
        git pull --rebase origin ${{ github.ref_name }} 2>/dev/null || true
        git add k8s/deployment.yaml
        git commit -m "ArgoCD Trigger: Actualizando imagen a version ${{ github.sha }}-${{ steps.version.outputs.current_version }} [skip ci]"
        git push origin ${{ env.REF }}